version: '3'
services:
  # mysql:
  #   image: mysql:5.6
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_USER: dbuser
  #     MYSQL_PASSWORD: userpass
  #     MYSQL_DATABASE: reviews
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - ./db_init/db.sql:/docker-entrypoint-initdb.d/db.sql
  app:
    build: ./app/.
    image: dmeng14/review_app
    depends_on:
      - db
    ports:
      - "8000:8000"
  # ingester:
  #   build: ./ingest/.
  #   image: dmeng14/ingest_review
  #   environment:
  #     RUN_MODE: local
  #   depends_on:
  #     - broker-backend
  # broker-backend:
  #   image: redis:4-alpine
  #   command: redis-server
  #   ports:
  #     - "6379:6379"
  # ingest-flower:
  #   build: ./ingest/.
  #   image: dmeng14/ingest_review
  #   depends_on:
  #     - broker-backend
  #   environment:
  #     RUN_MODE: flower
  #   ports:
  #     - "5555:5555"
